server:
  port: '8082'

spring:
  profiles:
    active: qa

---

spring:
  profiles: dev
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
welcome:
  message: Welcome to Daily Code Buffer!!

---

spring:
  profiles: qa
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
welcome:
  message: Welcome to Daily Code Buffer!!

---

spring:
  profiles: prod
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
welcome:
  message: Welcome to Daily Code Buffer!!